export * from './about.service';
import { AboutService } from './about.service';
export * from './accounts.service';
import { AccountsService } from './accounts.service';
export * from './attachments.service';
import { AttachmentsService } from './attachments.service';
export * from './autocomplete.service';
import { AutocompleteService } from './autocomplete.service';
export * from './availableBudgets.service';
import { AvailableBudgetsService } from './availableBudgets.service';
export * from './bills.service';
import { BillsService } from './bills.service';
export * from './budgets.service';
import { BudgetsService } from './budgets.service';
export * from './categories.service';
import { CategoriesService } from './categories.service';
export * from './charts.service';
import { ChartsService } from './charts.service';
export * from './configuration.service';
import { ConfigurationService } from './configuration.service';
export * from './currencies.service';
import { CurrenciesService } from './currencies.service';
export * from './data.service';
import { DataService } from './data.service';
export * from './insight.service';
import { InsightService } from './insight.service';
export * from './links.service';
import { LinksService } from './links.service';
export * from './objectGroups.service';
import { ObjectGroupsService } from './objectGroups.service';
export * from './piggyBanks.service';
import { PiggyBanksService } from './piggyBanks.service';
export * from './preferences.service';
import { PreferencesService } from './preferences.service';
export * from './recurrences.service';
import { RecurrencesService } from './recurrences.service';
export * from './ruleGroups.service';
import { RuleGroupsService } from './ruleGroups.service';
export * from './rules.service';
import { RulesService } from './rules.service';
export * from './search.service';
import { SearchService } from './search.service';
export * from './summary.service';
import { SummaryService } from './summary.service';
export * from './tags.service';
import { TagsService } from './tags.service';
export * from './transactions.service';
import { TransactionsService } from './transactions.service';
export * from './users.service';
import { UsersService } from './users.service';
export * from './webhooks.service';
import { WebhooksService } from './webhooks.service';
export const APIS = [AboutService, AccountsService, AttachmentsService, AutocompleteService, AvailableBudgetsService, BillsService, BudgetsService, CategoriesService, ChartsService, ConfigurationService, CurrenciesService, DataService, InsightService, LinksService, ObjectGroupsService, PiggyBanksService, PreferencesService, RecurrencesService, RuleGroupsService, RulesService, SearchService, SummaryService, TagsService, TransactionsService, UsersService, WebhooksService];
