/**
 * Firefly III API v2.1.0
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2024-05-19T04:33:01+00:00  Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that. 
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BillRepeatFrequency } from './billRepeatFrequency';


export interface BillUpdate { 
    /**
     * Use either currency_id or currency_code
     */
    currency_id?: string;
    /**
     * Use either currency_id or currency_code
     */
    currency_code?: string;
    name: string;
    amount_min?: string;
    amount_max?: string;
    date?: string;
    /**
     * The date after which this bill is no longer valid or applicable
     */
    end_date?: string;
    /**
     * The date before which the bill must be renewed (or cancelled)
     */
    extension_date?: string;
    repeat_freq?: BillRepeatFrequency;
    /**
     * How often the bill must be skipped. 1 means a bi-monthly bill.
     */
    skip?: number;
    /**
     * If the bill is active.
     */
    active?: boolean;
    notes?: string | null;
    /**
     * The group ID of the group this object is part of. NULL if no group.
     */
    object_group_id?: string | null;
    /**
     * The name of the group. NULL if no group.
     */
    object_group_title?: string | null;
}
export namespace BillUpdate {
}


