/**
 * Firefly III API v2.1.0
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2024-05-19T04:33:01+00:00  Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that. 
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BudgetSpent } from './budgetSpent';
import { AutoBudgetType } from './autoBudgetType';
import { AutoBudgetPeriod } from './autoBudgetPeriod';


export interface Budget { 
    readonly created_at?: string;
    readonly updated_at?: string;
    name: string;
    active?: boolean;
    notes?: string | null;
    readonly order?: number;
    auto_budget_type?: AutoBudgetType | null;
    /**
     * Use either currency_id or currency_code. Defaults to the user\'s default currency.
     */
    auto_budget_currency_id?: string | null;
    /**
     * Use either currency_id or currency_code. Defaults to the user\'s default currency.
     */
    auto_budget_currency_code?: string | null;
    auto_budget_amount?: string | null;
    auto_budget_period?: AutoBudgetPeriod | null;
    /**
     * Information on how much was spent in this budget. Is only filled in when the start and end date are submitted.
     */
    readonly spent?: Array<BudgetSpent>;
}
export namespace Budget {
}


