/**
 * Firefly III API v2.1.0
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2024-05-19T04:33:01+00:00  Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that. 
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChartDataPoint } from './chartDataPoint';


export interface ChartDataSet { 
    /**
     * This is the title of the current set. It can refer to an account, a budget or another object (by name).
     */
    label?: string;
    /**
     * The currency ID of the currency associated to the data in the entries.
     */
    currency_id?: string;
    currency_code?: string;
    currency_symbol?: string;
    /**
     * Number of decimals for the currency associated to the data in the entries.
     */
    currency_decimal_places?: number;
    start_date?: string;
    end_date?: string;
    /**
     * Indicated the type of chart that is expected to be rendered. You can safely ignore this if you want.
     */
    type?: string;
    /**
     * Used to indicate the Y axis for this data set. Is usually between 0 and 1 (left and right side of the chart).
     */
    yAxisID?: number;
    /**
     * The actual entries for this data set. They \'key\' value is the label for the data point. The value is the actual (numerical) value.
     */
    entries?: Array<ChartDataPoint>;
}

