/**
 * Firefly III API v2.1.0
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2024-05-19T04:33:01+00:00  Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that. 
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type DataDestroyObject = 'not_assets_liabilities' | 'budgets' | 'bills' | 'piggy_banks' | 'rules' | 'recurring' | 'categories' | 'tags' | 'object_groups' | 'accounts' | 'asset_accounts' | 'expense_accounts' | 'revenue_accounts' | 'liabilities' | 'transactions' | 'withdrawals' | 'deposits' | 'transfers';

export const DataDestroyObject = {
    NotAssetsLiabilities: 'not_assets_liabilities' as DataDestroyObject,
    Budgets: 'budgets' as DataDestroyObject,
    Bills: 'bills' as DataDestroyObject,
    PiggyBanks: 'piggy_banks' as DataDestroyObject,
    Rules: 'rules' as DataDestroyObject,
    Recurring: 'recurring' as DataDestroyObject,
    Categories: 'categories' as DataDestroyObject,
    Tags: 'tags' as DataDestroyObject,
    ObjectGroups: 'object_groups' as DataDestroyObject,
    Accounts: 'accounts' as DataDestroyObject,
    AssetAccounts: 'asset_accounts' as DataDestroyObject,
    ExpenseAccounts: 'expense_accounts' as DataDestroyObject,
    RevenueAccounts: 'revenue_accounts' as DataDestroyObject,
    Liabilities: 'liabilities' as DataDestroyObject,
    Transactions: 'transactions' as DataDestroyObject,
    Withdrawals: 'withdrawals' as DataDestroyObject,
    Deposits: 'deposits' as DataDestroyObject,
    Transfers: 'transfers' as DataDestroyObject
};

