/**
 * Firefly III API v2.1.0
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2024-05-19T04:33:01+00:00  Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that. 
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PiggyBank { 
    readonly created_at?: string;
    readonly updated_at?: string;
    /**
     * The ID of the asset account this piggy bank is connected to.
     */
    account_id: string;
    /**
     * The name of the asset account this piggy bank is connected to.
     */
    readonly account_name?: string;
    name: string;
    readonly currency_id?: string;
    readonly currency_code?: string;
    readonly currency_symbol?: string;
    /**
     * Number of decimals supported by the currency
     */
    readonly currency_decimal_places?: number;
    target_amount: string | null;
    readonly percentage?: number | null;
    current_amount?: string;
    readonly left_to_save?: string | null;
    readonly save_per_month?: string | null;
    /**
     * The date you started with this piggy bank.
     */
    start_date?: string;
    /**
     * The date you intend to finish saving money.
     */
    target_date?: string | null;
    order?: number;
    readonly active?: boolean;
    notes?: string | null;
    /**
     * The group ID of the group this object is part of. NULL if no group.
     */
    object_group_id?: string | null;
    /**
     * The order of the group. At least 1, for the highest sorting.
     */
    readonly object_group_order?: number | null;
    /**
     * The name of the group. NULL if no group.
     */
    object_group_title?: string | null;
}

