/**
 * Firefly III API v2.1.0
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2024-05-19T04:33:01+00:00  Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that. 
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RecurrenceTransactionUpdate { 
    id: string;
    description?: string;
    /**
     * Amount of the transaction.
     */
    amount?: string;
    /**
     * Foreign amount of the transaction.
     */
    foreign_amount?: string | null;
    /**
     * Submit either a currency_id or a currency_code.
     */
    currency_id?: string;
    /**
     * Submit either a currency_id or a currency_code.
     */
    currency_code?: string;
    /**
     * Submit either a foreign_currency_id or a foreign_currency_code, or neither.
     */
    foreign_currency_id?: string | null;
    /**
     * The budget ID for this transaction.
     */
    budget_id?: string;
    /**
     * Category ID for this transaction.
     */
    category_id?: string;
    /**
     * ID of the source account. Submit either this or source_name.
     */
    source_id?: string;
    /**
     * ID of the destination account. Submit either this or destination_name.
     */
    destination_id?: string;
    /**
     * Array of tags.
     */
    tags?: Array<string> | null;
    piggy_bank_id?: string | null;
    /**
     * Optional.
     */
    bill_id?: string | null;
}

